import { supabase } from '../lib/supabaseClient.js';
import { validateJanDataQuery } from './jandataQuerySchema.js';

/**
 * Execute a controlled JanData JSON query directly against Supabase database.
 * Strictly respects Row Level Security (RLS) policies.
 * 
 * @param {object} rawQuery - The controlled JSON query object generated by the frontend AI translator.
 * @returns {Promise<{ success: boolean, intent: string, data: any, error?: string }>}
 */
export async function executeJanDataQuery(rawQuery) {
  // 1. Validate controlled query schema
  const validation = validateJanDataQuery(rawQuery);
  if (!validation.valid) {
    return {
      success: false,
      intent: rawQuery?.intent || 'unknown',
      error: `Query Validation Failed: ${validation.error}`,
      data: null,
    };
  }

  const query = validation.query;

  try {
    switch (query.intent) {
      case 'query':
        return await handleSingleQuery(query);

      case 'compare_indicators':
      case 'cross_indicator_query':
        return await handleCompareIndicators(query);

      case 'cross_domain_query':
        return await handleCrossDomainQuery(query);

      case 'semantic_search':
        return await handleSemanticSearch(query);

      case 'hybrid':
        return await handleHybridQuery(query);

      default:
        return {
          success: false,
          intent: query.intent,
          error: `Unsupported query intent: ${query.intent}`,
          data: null,
        };
    }
  } catch (err) {
    console.error('[JanData Supabase Query Engine Error]:', err);
    return {
      success: false,
      intent: query.intent,
      error: err.message || 'An unexpected error occurred during database execution',
      data: null,
    };
  }
}

/**
 * Handle Intent 1: Single Indicator Query
 */
async function handleSingleQuery(query) {
  let dbQuery = supabase.from('observations').select('*');

  // Entity filtering
  if (query.entity) {
    if (query.entity.name) {
      dbQuery = dbQuery.eq('entity_name', query.entity.name);
    } else if (Array.isArray(query.entity.names) && query.entity.names.length > 0) {
      dbQuery = dbQuery.in('entity_name', query.entity.names);
    }

    if (query.entity.type) {
      dbQuery = dbQuery.eq('entity_type', query.entity.type);
    }
  }

  // Indicator filtering
  if (query.indicator) {
    dbQuery = dbQuery.eq('indicator', query.indicator);
  } else if (Array.isArray(query.indicators) && query.indicators.length > 0) {
    dbQuery = dbQuery.in('indicator', query.indicators);
  }

  // Domain & Time filtering
  if (query.domain) dbQuery = dbQuery.eq('domain', query.domain);
  if (query.year) dbQuery = dbQuery.eq('year', query.year);
  if (query.time?.year) dbQuery = dbQuery.eq('year', query.time.year);
  if (query.date) dbQuery = dbQuery.eq('date', query.date);
  if (query.period) dbQuery = dbQuery.eq('period', query.period);

  const { data, error } = await dbQuery;

  if (error) {
    return { success: false, intent: 'query', error: error.message, data: null };
  }

  return {
    success: true,
    intent: 'query',
    count: data ? data.length : 0,
    data: data || [],
  };
}

/**
 * Handle Intent 2: Compare Indicators / Cross-Indicator Join Query
 */
async function handleCompareIndicators(query) {
  const indicatorsList = query.indicators || query.select || [];
  const entityName = query.entity?.name || (query.entity?.names ? query.entity.names[0] : null);
  const targetYear = query.year || query.time?.year;

  let dbQuery = supabase.from('observations').select('*');

  if (entityName) {
    dbQuery = dbQuery.eq('entity_name', entityName);
  }
  if (query.entity?.type) {
    dbQuery = dbQuery.eq('entity_type', query.entity.type);
  }
  if (indicatorsList.length > 0) {
    dbQuery = dbQuery.in('indicator', indicatorsList);
  }
  if (targetYear) {
    dbQuery = dbQuery.eq('year', targetYear);
  }

  const { data, error } = await dbQuery;

  if (error) {
    return { success: false, intent: query.intent, error: error.message, data: null };
  }

  // Format into structured comparison object
  const structuredResult = {
    entity: entityName || 'Multiple',
    entity_type: query.entity?.type || 'district',
    year: targetYear || 'All Available',
    data: {},
  };

  if (data && data.length > 0) {
    for (const obs of data) {
      structuredResult.data[obs.indicator] = {
        value: obs.value,
        unit: obs.unit,
        source: obs.source_document,
        source_page: obs.source_page,
        domain: obs.domain,
        confidence: obs.confidence,
        extracted_at: obs.extracted_at,
        validation_flag: obs.validation_flag,
        validation_reason: obs.validation_reason,
      };
    }
  }

  return {
    success: true,
    intent: query.intent,
    data: structuredResult,
    raw_count: data ? data.length : 0,
  };
}

/**
 * Handle Intent 3: Cross-Domain Conditions Query
 */
async function handleCrossDomainQuery(query) {
  const conditions = query.conditions || [];
  const entityType = query.entity_type || query.entity?.type || 'district';
  const year = query.year || query.time?.year;

  const targetIndicators = conditions.map((c) => c.indicator);

  let dbQuery = supabase.from('observations').select('*');
  if (entityType) dbQuery = dbQuery.eq('entity_type', entityType);
  if (year) dbQuery = dbQuery.eq('year', year);
  if (targetIndicators.length > 0) dbQuery = dbQuery.in('indicator', targetIndicators);

  const { data, error } = await dbQuery;

  if (error) {
    return { success: false, intent: 'cross_domain_query', error: error.message, data: null };
  }

  // Group observations by entity_name
  const groupedByEntity = {};
  for (const obs of data || []) {
    if (!groupedByEntity[obs.entity_name]) {
      groupedByEntity[obs.entity_name] = {};
    }
    groupedByEntity[obs.entity_name][obs.indicator] = obs;
  }

  // Evaluate conditions for each entity
  const matchingEntities = [];

  for (const [entityName, entityObs] of Object.entries(groupedByEntity)) {
    let satisfiesAll = true;

    for (const cond of conditions) {
      const obs = entityObs[cond.indicator];
      if (!obs || obs.value === null || obs.value === undefined) {
        satisfiesAll = false;
        break;
      }

      const val = obs.value;
      const targetVal = cond.value;

      switch (cond.operator) {
        case '<':
          if (!(val < targetVal)) satisfiesAll = false;
          break;
        case '>':
          if (!(val > targetVal)) satisfiesAll = false;
          break;
        case '=':
        case '==':
          if (!(val === targetVal)) satisfiesAll = false;
          break;
        case '<=':
          if (!(val <= targetVal)) satisfiesAll = false;
          break;
        case '>=':
          if (!(val >= targetVal)) satisfiesAll = false;
          break;
        case '!=':
          if (!(val !== targetVal)) satisfiesAll = false;
          break;
        default:
          satisfiesAll = false;
      }

      if (!satisfiesAll) break;
    }

    if (satisfiesAll) {
      matchingEntities.push({
        entity_name: entityName,
        entity_type: entityType,
        year: year,
        observations: entityObs,
      });
    }
  }

  return {
    success: true,
    intent: 'cross_domain_query',
    matching_count: matchingEntities.length,
    data: matchingEntities,
  };
}

/**
 * Handle Intent 4: Semantic Search in document_chunks
 */
async function handleSemanticSearch(query) {
  const searchQuery = query.query || '';
  const domain = query.domain;

  let dbQuery = supabase.from('document_chunks').select('*');

  if (domain) {
    dbQuery = dbQuery.eq('domain', domain);
  }

  // Break search query into keywords for flexible text searching
  const keywords = searchQuery
    .split(/\s+/)
    .filter((w) => w.length > 3)
    .map((w) => w.toLowerCase());

  if (keywords.length > 0) {
    // Search using ilike matching for keywords
    const orFilter = keywords.map((kw) => `chunk_text.ilike.%${kw}%`).join(',');
    dbQuery = dbQuery.or(orFilter);
  } else if (searchQuery) {
    dbQuery = dbQuery.ilike('chunk_text', `%${searchQuery}%`);
  }

  // Limit chunk results to top 10 relevant items
  dbQuery = dbQuery.limit(10);

  const { data, error } = await dbQuery;

  if (error) {
    return { success: false, intent: 'semantic_search', error: error.message, data: null };
  }

  return {
    success: true,
    intent: 'semantic_search',
    query: searchQuery,
    chunks_found: data ? data.length : 0,
    data: data || [],
  };
}

/**
 * Handle Intent 5: Hybrid Query (Structured + Document Text)
 */
async function handleHybridQuery(query) {
  const structuredQueryObj = query.structured || { intent: 'query' };
  const semanticQueryObj = query.semantic || { intent: 'semantic_search', query: '' };

  const [structuredRes, semanticRes] = await Promise.all([
    executeJanDataQuery(structuredQueryObj),
    executeJanDataQuery(semanticQueryObj),
  ]);

  return {
    success: structuredRes.success && semanticRes.success,
    intent: 'hybrid',
    data: {
      structured_observations: structuredRes.data,
      document_chunks: semanticRes.data,
    },
    errors: {
      structured_error: structuredRes.error || null,
      semantic_error: semanticRes.error || null,
    },
  };
}
